# frozen_string_literal: true

require 'fileutils'
require 'json'
require_relative '../../core/logger'

module SjuiTools
  module SwiftUI
    module Generators
      class ConverterGenerator
        def initialize(name, options = {})
          @name = name
          @class_name = to_camel_case(name) + "Converter"
          @options = options
          @logger = Core::Logger
        end

        def generate
          @logger.info "Generating custom converter: #{@class_name}"
          
          # Create converter file
          create_converter_file
          
          # Update mappings file
          update_mappings_file
          
          @logger.success "Successfully generated converter: #{@class_name}"
          @logger.info "Converter file created at: views/extensions/#{@name}_converter.rb"
          @logger.info "Mappings file updated with '#{to_camel_case(@name)}' => '#{@class_name}'"
        end

        private

        def create_converter_file
          # Ensure views/extensions directory exists
          extensions_dir = File.join(Dir.pwd, 'tools', 'sjui_tools', 'lib', 'swiftui', 'views', 'extensions')
          FileUtils.mkdir_p(extensions_dir)
          
          file_path = File.join(extensions_dir, "#{@name}_converter.rb")
          
          if File.exist?(file_path)
            @logger.warn "Converter file already exists: #{file_path}"
            print "Overwrite? (y/n): "
            response = gets.chomp.downcase
            return unless response == 'y'
          end
          
          File.write(file_path, converter_template)
          @logger.info "Created converter file: #{file_path}"
        end
        
        def update_mappings_file
          mappings_file = File.join(Dir.pwd, 'tools', 'sjui_tools', 'lib', 'swiftui', 'views', 'extensions', 'converter_mappings.rb')
          
          # Create new mappings file if it doesn't exist
          if !File.exist?(mappings_file)
            create_initial_mappings_file
            return
          end
          
          # Read existing mappings
          content = File.read(mappings_file)
          
          # Check if mapping already exists
          component_type = to_camel_case(@name)
          if content.include?("'#{component_type}' =>")
            @logger.warn "Mapping for '#{component_type}' already exists in converter_mappings.rb"
            return
          end
          
          # Add new mapping
          new_mapping = "          '#{component_type}' => '#{@class_name}',"
          
          # Insert the new mapping before the closing brace of CONVERTER_MAPPINGS
          content.sub!(/(CONVERTER_MAPPINGS = \{[^}]*)(        \}\.freeze)/m) do
            existing_mappings = $1
            closing = $2
            
            # Add comma to last mapping if there are existing mappings
            if existing_mappings =~ /[^{\s]/
              "#{existing_mappings}\n#{new_mapping}\n#{closing}"
            else
              "#{existing_mappings}\n#{new_mapping}\n#{closing}"
            end
          end
          
          File.write(mappings_file, content)
          @logger.info "Updated converter_mappings.rb with new mapping"
        end
        
        def create_initial_mappings_file
          mappings_file = File.join(Dir.pwd, 'tools', 'sjui_tools', 'lib', 'swiftui', 'views', 'extensions', 'converter_mappings.rb')
          
          content = <<~RUBY
            # frozen_string_literal: true
            
            # This file maps custom component types to their converter classes
            # Auto-generated by sjui g converter command
            
            module SjuiTools
              module SwiftUI
                module Views
                  module Extensions
                    CONVERTER_MAPPINGS = {
                      '#{to_camel_case(@name)}' => '#{@class_name}',
                    }.freeze
                  end
                end
              end
            end
          RUBY
          
          File.write(mappings_file, content)
          @logger.info "Created converter_mappings.rb with initial mapping"
        end

        def converter_template
          attributes_code = generate_attributes_code
          
          <<~RUBY
            # frozen_string_literal: true
            
            require_relative '../../converters/base_converter'
            
            module SjuiTools
              module SwiftUI
                module Views
                  module Extensions
                    class #{@class_name} < Converters::BaseConverter
                    def convert
                      result = []
                      
                      # Component name
                      result << "\#{indent}#{to_camel_case(@name)} {"
                      
                      @indent_level += 1
                      
                      #{attributes_code}
                      
                      # Convert children if present
                      if @component['children']
                        @component['children'].each do |child|
                          child_converter = @factory.create_converter(child, @indent_level, @action_manager, @registry, @binding_registry)
                          result.concat(child_converter.convert)
                        end
                      end
                      
                      @indent_level -= 1
                      result << "\#{indent}}"
                      
                      result
                    end
                    
                    private
                    
                    def component_name
                      "#{to_camel_case(@name)}"
                    end
                    end
                  end
                end
              end
            end
          RUBY
        end

        def generate_attributes_code
          lines = []
          
          if @options[:use_default_attributes]
            lines << "# Default attributes"
            lines << "apply_default_attributes(result)"
            lines << ""
          end
          
          if @options[:attributes] && !@options[:attributes].empty?
            lines << "# Custom attributes"
            @options[:attributes].each do |key, type|
              lines << "if @component['#{key}']"
              lines << "  result << \"\#{indent}.#{key}(@component['#{key}'])\""
              lines << "end"
              lines << ""
            end
          end
          
          lines.join("\n                  ")
        end

        def to_camel_case(str)
          str.split('_').map(&:capitalize).join
        end
      end
    end
  end
end