# frozen_string_literal: true

# This file maps custom component types to their converter classes
# Auto-generated by sjui g converter command

module SjuiTools
  module SwiftUI
    module Views
      module Extensions
        CONVERTER_MAPPINGS = {
          'TestComponent' => 'TestComponentConverter',
          'CustomButton' => 'CustomButtonConverter',
          'SampleCard' => 'SampleCardConverter',
          'TestBanner' => 'TestBannerConverter',
        }.freeze
      end
    end
  end
end
