//
//  CodegenFixtureRegistryDefault.swift
//  ConformanceHost
//
//  Compile-time default for the codegen fixture registry. The REAL registry
//  is @generated by scripts/generate_codegen_host.rb into
//  CodegenStaging/CodegenFixtureRegistry.swift (a switch over every
//  ios-applicable visual fixture, returning the sjui-generated view).
//
//  scripts/generate_project.rb includes EITHER this default OR the generated
//  staging sources — never both — so the app always compiles: without the
//  staging output the host still builds and runs the dynamic pipeline;
//  CONFORMANCE_HOST_MODE=codegen then reports every fixture as
//  conformance_load_error instead of hanging.
//

import SwiftUI

enum CodegenFixtureRegistry {
    /// Launch-time wiring for the generated pipeline (resource providers).
    /// No-op here: the generated registry overrides it with the consumer
    /// contract (colorProvider → generated ColorManager).
    static func activate() {}

    static func view(for fixtureId: String) -> AnyView? {
        nil
    }
}
